.TH JOINTRIS 1
.SH NAME
jointris \- Joinable tetris blocks with bombs
.SH SYNOPSIS
.TP 5
\fBjointris\fR [\fIOPTION\fR]
.RI 
.br

.SH OPTIONS
.PP
.br
\fB   --touch\fR             Start in touch mode.
.br
.br
\fB-s --no-sound\fR          Disables sound;
                       more efficient than setting volume(s) to 0.
.br
.br
\fB-f --fullscreen\fR        Start in fullscreen.
.br
.br
\fB-t --testing\fR           Enable testing of custom games and themes.
.br
.br
\fB-v --version\fR           Prints version.
.br
.br
\fB-h --help\fR              Prints this message.

.SH DESCRIPTION
.PP
Tetris like game with multiple joinable blocks.

.PP
Features:
.br
 - multiple blocks that can be joined together
.br
 - multiple players collaborating or competing
.br
 - custom shaped blocks and weird rotations
.br
 - exploding bombs
.br

.PP
Note:
.br
When started with --touch only single player games can be played.
.br
The game's window is partitioned in eight cells (over two columns).
.br
Each cell is associated with an action:
.br
- Pause  - Next
.br
- Down   - Next
.br
- Drop   - Rotate
.br
- Left   - Right
.br

.SH AUTHOR
.PP
Written by Stefano Marsili <efanomars@gmx.ch>.

.SH LICENSE
.PP
Copyright © 2019-2020 Stefano Marsili.

.PP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
